### ISSUE TITLE
meta git update fails with "TypeError: Cannot read property 'projects' of null" in metaGitUpdate.js:16

### ISSUE THREAD

**Issue by ljcrapo** [mateodelnorte/meta-git#16]
```
$ meta git update
C:\Users\user\AppData\Roaming\npm\node_modules\meta\node_modules\meta-git\lib\metaGitUpdate.js:16
  const projects = meta.projects;
                        ^

TypeError: Cannot read property 'projects' of null
    at module.exports (C:\Users\user\AppData\Roaming\npm\node_modules\meta\node_modules\meta-git\lib\metaGitUpdate.js:16:25)
    at Object.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\meta\node_modules\meta-git\bin\meta-git-update:13:32)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

**Comment by mateodelnorte** [comment]
I'm betting you have a typo, perhaps an extra or missing comma, in your .meta file. We could use a better error here.

**Comment by ljcrapo** [comment]
Sure enough, that was the problem! A better error here would definitely be helpful.

**Comment by mateodelnorte** [comment]
Care to try a PR?
